### PR TITLE
POST formdata to create torrents (including mutable ones)

### PR DESCRIPTION
**Pull request by RangerMauve**
Supercedes #2 

Not ready to merge yet, but submitting a PR for comments / contrib. Big thanks to @resession for laying down the groundwork!

- [x] `POST` to `bittorrent://$/` to create a new torrent with just the infohash.
  - Can't put files into subfolders due to limitations of `FormData` 🙃
- [x] `POST` to `bittorrent://PETNAME` to derive a public-private keypair from a seed key
  - [x] Update files in root dir
  - [x] Take the `pathname` into account to create subfolders
- [x] `POST` to `bittorrent://PUBLIC_KEY` with `Authorization` header containing `secret`
  - [x] Try to fetch the existing `name` from the torrent if one is not provided. 
  - [ ] If the `name` changes, move the files from the old name to the new name
 - [x] Detect updates to mutable torrents by periodically polling (+re-seeding in the DHT)
   - [ ] Detect when the `name` changes and copy over the files to the new named directory + re-verify the contents

### CODE REVIEW

**Comment by resession** [comment]
posting this from discord since it is more relevant here, referring to the `GET bittorrent://B9D3E9224F8411B35AC696EFEDCC97BCF85238CC/` test that always returned a "not found" error

"the relativepath property is used on `.map()` but i think `.filter()` is where the problem is.
starts with https://github.com/RangerMauve/bt-fetch/blob/mutable-post/index.js#L108 the regular file.path property is used here
and filter is where it happens https://github.com/RangerMauve/bt-fetch/blob/mutable-post/index.js#L193
when the path is the index(`/`), then it makes a literal / so on the filter when the file.path is used(which on windows will have \ separator and starts with drive letter), the / literal will not work"

**Comment by resession** [comment]
for the `DELETE`, https://github.com/RangerMauve/bt-fetch/blob/mutable-post/index.js#L158, i am not seeing a `deleteTorrent()` function in the Torrent-Manager.js file. wondering if its there temporarily and we will add that function in the torrent-manager.js file later.

**Comment by RangerMauve** [comment]
Oh yeah, I haven't gotten to DELETE yet. 😅

**Comment by resession** [comment]
i'll be online off and on and then i'll be back in the weekend after my work is over for the week. i'll look at the code more to understand the details, then i can try to contribute and help out.

**Comment by resession** [comment]
posting this from discord since it is more relevant here, referring to the GET bittorrent://B9D3E9224F8411B35AC696EFEDCC97BCF85238CC/ test that always returned a "not found" error

"the relativepath property is used on .map() but i think .filter() is where the problem is.
starts with https://github.com/RangerMauve/bt-fetch/blob/mutable-post/index.js#L108 the regular file.path property is used here
and filter is where it happens https://github.com/RangerMauve/bt-fetch/blob/mutable-post/index.js#L193
when the path is the index(/), then it makes a literal / so on the filter when the file.path is used(which on windows will have \ separator and starts with drive letter), the / literal will not work"

fixed it on my bt-fetch repo.

i used `.filter(({ relativePath }) => relativePath.startsWith(directoryPath))` instead of `.filter(({ path }) => path.startsWith(directoryPath))`
https://github.com/resession/bt-fetch/blob/default/index.js#L193

**Comment by resession** [comment]
i commentted the `map.delete()` out from the `deleteTorrent()` function. i saw that the torrents are deleted from the `map` on the `close` event.

**Comment by resession** [comment]
on the `_trackTorrent` function, i had an idea. we can make a setInterval timer on each torrent to check the dht on a timer to see if it is current. if it not current, then it can destroy itself. BUT if someone has over 100 torrent then that is a lot of timers. i don't know what impact it will have on memory/cpu usage. if that is too impractrical than we can use a for loop and update the torrents that way.

**Comment by RangerMauve** [comment]
K, I think this is good to go! There's still the TODOs for dealing with the `name` changing, but I think it'd be fine to punt that until later and treat it as "If you change the name, existing data will get wiped" for now.

**Comment by resession** [comment]
all my computers(1 linux, 2 windows) have the writing empty files problem. can you test creating a mutable-torrent in another machine on your end? seems like it works for your machine but doesn't work for my machines. strange problem.

**Comment by resession** [comment]
i'm currently using this pr in the agregore-browser repo in my linux computer. got a porblem. here is the step by step to reproduce the problem.

1. visit bittorrent site
2. close agregore
3. visit same bittorrent site
4. get error `Error: cannot add duplicate torrent`

seems like it tries to download the torrent again, even though the torrent is already active in webtorrent

EDIT: i'm getting this problem on windows too

**Comment by RangerMauve** [comment]
@resession Still can't repro the empty files thing. 🤔 Are any of the other fetch libraries having that issue?

Also, is the site you mentioned using mutable torrents or an infohash?

**Comment by RangerMauve** [comment]
Fixed up the tests a bit. It seems files being missing can't be reproduced with this repo. If we're having those issues still, it might be worth it to look into doing separate tests in an electron repo. 🤷

**Comment by RangerMauve** [comment]
Out in 3.0.0 I'll try including it in the next agregore release

**Pull request merged**
