### PR TITLE
small change to resolve public keys

### PR DESCRIPTION
**Pull request by resession**
added webproperty module to add ability to resolve public key

### CODE REVIEW

**Review by RangerMauve — APPROVED** [review]
This looks awesome, thank you.

Is there a seeded mutable archive I could test this with before we release?

it might be nice to add a mutable URL to the `example.js` for people to test with. Or maybe to the README?

**Comment by resession** [comment]
yeah, i'll add something on the example.js or readme.

**Comment by resession** [comment]
yeah, i'll add something in there.

**Comment by resession** [comment]
added how a publickey url should look like in the readme, i wanted to add something in example.js but i don't know any torrents out there that are mutable/bep46.

**Comment by RangerMauve** [comment]
Cool, we can have the example mutable torrent be a TODO for later. Having info on what the URLs look like is a good start.

I might want to set up a seeding service kinda like dat-store which I'd run on my Digital Ocean droplet and have stuff synced on there (maybe the Agregore website?) 😁

**Comment by RangerMauve** [comment]
Thank you for taking this on! Gonna release a new version in a sec and then get it into Agregore.

**Comment by RangerMauve** [comment]
Published in 2.0.0

**Pull request merged**
